from .base import DashboardWidget
from .kpi_cards import KpiCardsWidget
from .course_summary import CourseSummaryWidget
from .heatmap import HeatmapWidget
from .alerts import AlertsWidget
from .activity_feed import ActivityFeedWidget
from .quick_actions import QuickActionsWidget
from .evolution import EvolutionWidget
from .documents import DocumentsWidget
